version: '3'
name: 'ewt'

volumes:
  ewt-postgres_data:
      driver: local
  ewt-minio_data: {}

services:
  ewt-postgres:
    image: postgres
    volumes:
      - ewt-postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ewt
      POSTGRES_USER: ewt
      POSTGRES_PASSWORD: ewt
    ports:
      - 5432:5432
  ewt-minio:
    image: minio/minio
    volumes:
      - ewt-minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment: 
      MINIO_ROOT_USER: minio-admin
      MINIO_ROOT_PASSWORD: minio-admin
    command: server --console-address ":9001" /data
