# ===================================================================
# Standard Spring Boot properties.
# ===================================================================

server:
  port: 9103

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    ewt.msvc.config: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  cloud:
    config:
      uri: http://admin:${jhipster.registry.password}@localhost:8761/config
      name: ewt-msvc-cart
      profile: dev
      label: main
  liquibase:
    contexts: dev, faker
    url: jdbc:postgresql://localhost:5432/ewt
    default-schema: ewt_cart
  messages:
    cache-duration: PT1S
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ewt
    username: ewt
    password: ewt
  thymeleaf:
    cache: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  registry:
    password: admin
  # cors:
  #   allowed-origins: "*"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   exposed-headers: "Authorization,Link,X-Total-Count"
  #   allow-credentials: true
  #   max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: MzEzN2Y5ZDRiODQwNTgwMGMwOTk3NTZkNzUxMTQyY2FjN2UyOWEwNDY0Mjc5Zjc1ODJlODU3NGRhZDQ2NWI5ZjY2MTk1NTA0OGUwNTJhZjU2NzM0NGQ4YjgzYjU4YWNhNzU5NTdmMTU1OWI3MTcwOTcwNzYxYTg2ZmVmMjA2MjM=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# ===================================================================
# Application specific properties
# ===================================================================

# application:
